import '../globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AYG3\'s site generated by next and sanity',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <main>{children}</main>
      </body>
    </html>
  )
}
