import { getPages } from '@/sanity/sanity-utils';
import '../globals.css'
import type { Metadata } from 'next'
import Link from 'next/link';


export const metadata: Metadata = {
  title: 'AYG3\'s site generated by next and sanity',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  //get all pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className='flex items-center justify-between'>
          <Link href="/" className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-500 bg-clip-text text-transparent text-lg font-bold" >AYG3 </Link>  

          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className='hover:underline transition'> 
                {page.title}
              </Link>
            ))}
          </div>
        </header>


        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
